---
l2_interfaces:
  - name: Ethernet0/1
    mode: access
    access:
      vlan: 10
  - name: Ethernet0/2
    mode: access
    access:
      vlan: 20
  - name: Ethernet0/3
    mode: access
    access:
      vlan: 30
