---
l2_interfaces:
  - name: Ethernet0/1
    mode: access
    access:
      vlan: 10
  - name: Ethernet0/2
    mode: access
    access:
      vlan: 20
  # - name: Ethernet0/3
  #   mode: access
  #   access:
  #     vlan: 30
  # - name: Ethernet0/3
  #   mode: access
  #   access:
  #     vlan: 30

  - name: Ethernet0/3
    mode: trunk
    trunk:
      encapsulation: dot1q
      native_vlan: 1
      allowed_vlans: 10,20,30
