---
interfaces:
  - name: Ethernet1
    description: to-rtr1
    ipv4:
      - address: 10.0.0.2/30
    enabled: true
    state: present
  - name: Ethernet2
    description: to-sw2
    ipv4:
      - address: 192.168.1.2/24
    enabled: true
    state: present
  - name: Loopback0
    description: loopback
    ipv4:
      - address: 2.2.2.2/32
    enabled: true
    state: present
